name: Workflow Canceler
on: push

jobs:
  cancel:
    name: Cancel this workflow 
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 3
          echo "done"
      #    curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID/cancel"
