name: Workflow Canceler
on: push

jobs:
  cancel:
    name: Cancel this workflow 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: |
          ./sleep.sh
