name: Cancel Eraser
on: push

jobs:
  erase:
    name: Delete canceled workflows 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      RUN_ID: ${{ github.run_id }}
    steps: 
      - run | curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <YOUR-TOKEN>" https://api.github.com/repos/$OWNER/$REPO/actions/runs
