name: Get Runner Arch
on: push

jobs:
  getArch:
    name: Get Arch of every OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    steps:
       - name: actions/checkout@v3
         shell: bash
         run: echo ${{ runner.arch }}
