name: CI Build Ubuntu
on: push
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'push' }}
        run: test -z $(git rev-list  --before="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        
      - id: test
        if: ${{ check_date.outputs.should_run != 'false' }}
        run: echo ${{ check_date.outputs.should_run }}
  Integration-Test:
    runs-on: ubuntu-latest
    needs: check_date
    if: ${{ needs.check_commit.outputs.should_run != 'false' }}
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: set an output to test
        id: Test1
        run: echo "test"
      
