name: CI Build Ubuntu
on: push
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    env:
      TEST: $WAS_EDITED
    outputs:
      WAS_EDITED: ${{ steps.check_date.outputs.WAS_EDITED }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: check_date
        #continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'push' }}
        #run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false" && exit 1
        run: echo '::set-output name=WAS_EDITED::'$(test -n "$(git log --format=%H --since='72 hours ago')" && echo 'true' || echo 'false')
        
      - id: tester
        name: tester
        if: test -n "$(git log --format=%H --since='72 hours ago')
        #if: ${{ needs.check_date.outputs.WAS_EDITED == 'true' }}
        run: echo env.TEST
        
  Integration-Test:
    runs-on: ubuntu-latest
    needs: check_date
    if: ${{ needs.check_date.outputs.WAS_EDITED == 'true' }}
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: check latest commit
        id: Test
        run: |
          export TEST="test"
          echo $TEST
      - name: output
        run: echo $TEST
      
