name: CI Build Ubuntu
on: push
jobs:
  check_commit:
    uses: alfeilex/git-action-sandbox/.github/workflows/commit-check.yml@master
  build:
    runs-on: ubuntu-latest
    needs: check_commit
    if: ${{ needs.check_commit.outputs.should_run != 'false' }}
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: set an output to test
        id: Test1
        run: echo "test"
      
