name: Test
on: push
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    steps:
      - uses: actions/checkout@v2
      
      - id: check_commit
        name: Check latest commit is less than 24 hours
        if: ${{ github.event_name == 'push' }}
        run: echo '::set-output name=should_run::'$(test -n "$(git log --format=%H --since='72 hours ago')" && echo 'true' || echo 'false')
 
  cancel:
    runs-on: ubuntu-latest
    name: Check latest commits
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: ${{ github.event.workflow.id }}
          access_token: ${{ github.token }}
  
  asdasd:
    runs-on: ubuntu-latest
    name: Check latest cossadasd
    steps:
      - uses: actions/checkout@v2
      
      - id: test
        run: echo "test"
