name: CI Files should be terminated by newline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Next test
        continue-on-error: true
        run: exit 1
      - name: Detect CRLF line endings
        run: | 
          find . -type f | xargs file | grep CRLF && exit 1 || exit 0
