name: Test
on: push
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    steps:
      - uses: actions/checkout@v2
      
      - id: check_commit
        name: Check latest commit is less than 24 hours
        if: ${{ github.event_name == 'push' }}
        run: echo '::set-output name=should_run::'$(test -n "$(git log --format=%H --since='72 hours ago')" && echo 'true' || echo 'false')
 
  build:
    needs: check_date
    if: ${{ check_date.check_commit.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "yes"
 
 
  cancel:
    needs: check_date
    if: ${{ check_date.check_commit.outputs.should_run == 'false' }}
    runs-on: ubuntu-latest
    name: Cancel the current workflow
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: |
          curl -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID"

          
    #curl -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID"

