name: CI Build Ubuntu
on: push
env:
      TEST: $WAS_EDITED
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    steps:
      - uses: actions/checkout@v2
      
      - id: check_commit
        name: Check latest commit is less than 24 hours
        if: ${{ github.event_name == 'push' }}
        run: echo '::set-output name=should_run::'$(test -n "$(git log --format=%H --since='72 hours ago')" && echo 'false' || echo 'false')
 
      - id: Tester
        name: tester
        if: ${{ steps.check_commit.outputs.should_run == 'true' }}
        run: echo "testerewewe"
        
