name: Test Colors Outpu
on: push

jobs:
  check_colors:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Run script
        run: |
          cmd 
