name: CI Build Ubuntu
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/hello-world-javascript-action@v1.1
        if: ${{ grep -r "comadasd" }}
